version: "3.8"
services:
  nginx:
    container name: nginx
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    container name: flask-app
    image: flask-app:latest
    build: .
    environment:
      YOUR_NAME: $(YOUR_NAME)
    